
cmake_minimum_required(VERSION 2.6)
if(POLICY CMP0011)
    cmake_policy(PUSH)
    cmake_policy(SET CMP0011 NEW)
endif(POLICY CMP0011)

macro(macro_delete_installed)
    foreach(_glob ${ARGN})
        install(CODE "
                if(POLICY CMP0011)
                    cmake_policy(SET CMP0011 NEW)
                endif(POLICY CMP0011)
                set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH})
                include(MacroInstallPrefix)
                macro_install_prefix(_install_prefix)
                set(old_installed)
                file(GLOB old_installed \"\${_install_prefix}/${_glob}\")
                if(old_installed)
                    foreach(oi \${old_installed})
                        message(STATUS \"Removing:   \${oi}\")
                        file(REMOVE \"\${oi}\")
                    endforeach(oi \${old_installed})
                endif(old_installed)
        ")
    endforeach(_glob ${ARGN})
endmacro(macro_delete_installed)

if(POLICY CMP0011)
    cmake_policy(POP)
endif(POLICY CMP0011)

